apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: nginx
