apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehealth-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: e-health
          image: mire12/e-health:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
